name: 'publish packages'

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com
          scope: '@deadbotgg'
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: configure package for github registry
        run: |
          # Create a temporary package.json for GitHub packages
          cp package.json package.json.npm
          sed -i 's/@deadbot\/types/@deadbotgg\/types/g' package.json
          sed -i 's/https:\/\/registry.npmjs.org/https:\/\/npm.pkg.github.com/g' package.json
      - name: publish to github packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: restore original package.json
        run: mv package.json.npm package.json
